### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by cboettig**
Fixed the noise scaling for the log-normal case.  (variance of data we match to is mu * sigma^2 / 3, not sigma^2 / 3; since I don't rescale mu to 1)

Also wasn't running uniform case (since argument wasn't passed).  Running solutions again now.

### CODE REVIEW

**Comment by jeroenooms** [comment]
Do you need help with this?

**Comment by cboettig** [comment]
@jeroenooms Thanks for the ping. No, sorry, meant this to be an internal PR against my fork.  We've been doing some pretty interesting work just using these algorithms, and I've just been adding some higher-level wrappers to the package on my fork as we go along.  Been meaning to merge everything back here at some point, and perhaps write up a short methods paper which I think would help more R users take advantage of the pretty powerful algorithms here that my field has largely ignored since they've been pretty inaccessible.  Obviously we'd like to rope you in as an author on that; but right now the research-stage has helped me figure out more about what I need the higher-level interface to do.  Still tweaking around the edges but should have that finalized soon.

While we're on the topic though, I thought I might mention: when I run check locally on my ubuntu machine (or rather my docker image) I get a lot of C++ warnings about places in the C code that convert strings to 'char*', e.g. 

```
* checking whether package ‘appl’ can be installed ... WARNING
Found the following significant warnings:
  pomdp_spec.y:223:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
```

yet I don't see that warning on Travis.  Any idea why or if that can be easily resolved without editing all the C code?

**Comment by jeroenooms** [comment]
It depends on the version of gcc that you use and if you have `-Wall` in the Rprofile `CFLAGS`.

Don't think there is an easy fix, better to try and report compiler warnings upstream. I wouldn't really know how to fix the warnings, and I'm afraid trying to hack it in might have unexpected side effects.

**Comment by cboettig** [comment]
Ok, thanks. Does CRAN require `-Wall` flag when it builds the package?

**Comment by jeroenooms** [comment]
You should check with `--as-cran` to see if warnings are ignorable or not.

**Comment by cboettig** [comment]
right, but I don't suppose there's some way to just have R compile without `-Wall` by fiddling with Makevars or something?

**Comment by jeroenooms** [comment]
No, CRAN specifically adds that flag locally to test for non-portable code...

**Pull request closed without merging**
